import { Injectable } from '@angular/core';
import {
  Boom,
  Feature,
  Geometry,
  MechLeiding,
  Rioolput,
  VrijvLeiding,
  Wegvakonderdeel,
  Wegvakonderdeelplanning,
} from '../generated';
import { FormHelpers } from '../../feature-form/form/form-helpers';


@Injectable({
  providedIn: 'root',
})
export class FeatureInitializerService {

  public static enum

  public static readonly STUB_OBJECT_GUID_NEW_OBJECT = '-1';

  constructor() {
  }

  public retrieveGeometry(feature: Feature): Geometry {
    switch (feature.objecttype) {
      case 'Wegvakonderdeel':
        return (feature as Wegvakonderdeel).geometrie;
      case 'Rioolput':
        return (feature as Rioolput).geometrie;
      case 'Mechleiding':
        return (feature as MechLeiding).geometrie;
      case 'Vrijvleidin':
        return (feature as VrijvLeiding).geometrie;
      case 'Boom':
        return (feature as Boom).geometrie;
    }
    return null;
  }

  public create(type: string, params: any): Feature {
    params.clazz = type.toLowerCase();
    params.objecttype = FormHelpers.snakecaseToCamel(type);
    params.objectGuid = FeatureInitializerService.STUB_OBJECT_GUID_NEW_OBJECT;
    switch (type) {
      case 'Wegvakonderdeel':
        const wv: Wegvakonderdeel = {
          aanlegjaar: 0,
          aanzien: '',
          beheerder: '',
          bestek_nr: '',
          binnen_kom: '',
          breedte: 0,
          children: [],
          comfort: '',
          duurzaamheid: '',
          fid: 0,
          functie_weg: '',
          functie_weg_plus: '',
          fysiekvoorkomenwegplus: '',
          geometrie: undefined,
          id: 0,
          lengte: 0,
          openbare_ruimte: '',
          oppervlakte: 0,
          rijstrook: '',
          std_structuurelement: '',
          veiligheid: '',
          verhardingsfunctie: '',
          verhardingssoort: '',
          verhardingstype: '',
          wegtype: '',
          wijk: '',
          woonplaats: '',
          ...params,
        };
        return wv;
      case 'Wegvakonderdeelplanning':
        const wvp: Wegvakonderdeelplanning = {
          children: null,
          fid: 0,
          geometrie: undefined,
          hoeveelheid: 0,
          id: 0,
          jaarvanuitvoering: 0,
          kosten: 0,
          maatregel_wvko: '',
          maatregeltype: '',
          wegvakonderdeel_id: '',
          ...params,
        };
        return wvp;
      case 'Rioolput':
        const rp: Rioolput = {
          aanlegjaar: 0,
          aansluitend_stelseltype: '',
          aant_aansl_inw_recr: 0,
          aant_aansl_inwoner: 0,
          aantal_aansl_bedrijven: 0,
          aantal_aansl_diversen: 0,
          aantal_aansl_horeca: 0,
          aantal_aansl_kolken: 0,
          aantal_aansl_woningen: 0,
          aantal_aansl_woonboten: 0,
          aantal_pompen: 0,
          afbeelding: '',
          afspraak_waterschap: '',
          afwijkendedieptelegging: 0,
          bbv: '',
          begin_tijd: '',
          beheercluster: '',
          beheerder: '',
          beheerder_vakgeb: '',
          bergend_oppervlak: 0,
          bestek: '',
          bestek_nr: '',
          bouwjaar_pomp: 0,
          bovengrondszichtbaar: '',
          breedte: 0,
          breedte_toegang: 0,
          bronhouder: '',
          buurt: '',
          categorie: '',
          children: undefined,
          clazz: '',
          continue_lozing: 0,
          dab_scheur: 0,
          dac_breuk_instorting: 0,
          dad_defect_metselwerk: 0,
          daf_schade_oppervlak: 0,
          datum_maaiveldhoogte: '',
          dba_wortels: 0,
          dbd_binnendringen_grond: 0,
          dbf_infiltratie: 0,
          diameter: 0,
          diameter_doorlaat: 0,
          diameter_persaansluiting: 0,
          diepte: 0,
          domein: '',
          drempel_breedte: 0,
          drempelhoogte_nap: 0,
          eind_tijd: '',
          fid: 0,
          funderingstype: '',
          geleiding: '',
          gem_emissie_jaar: 0,
          gem_emissie_jaar_bzv: 0,
          gemeente: '',
          geometrie: undefined,
          geonauwkeurigheidxy: 0,
          geotextiel_inf_deel: '',
          grondeigendom: '',
          grondsoort: '',
          grondwaterstand: 0,
          hoofdcategorie: '',
          hoogte_put: 0,
          hoogteligging_doorlaat: 0,
          hoogteligging_obl: 0,
          hoogwaterpeil: 0,
          hulpputcode: '',
          id: 0,
          imgeo_id: '',
          in_onderzoek: '',
          inschakelpeil: 0,
          inspectiedatum: '',
          int_putmateriaal: '',
          invoer: 0,
          kleptype: '',
          knoopnummer: '',
          laagwaterpeil: 0,
          lengte: 0,
          lengte_putdeel: 0,
          lengte_toegang: 0,
          leverancier_fabrikant: '',
          locatie: '',
          maaiveldhoogte: 0,
          maaiveldhoogte_actueel: 0,
          maaiveldhoogte_ontwerp: 0,
          mantoegankelijk: '',
          materiaal_gwsw: '',
          materiaal_inf_deel: '',
          materiaal_put: '',
          niv_buitenwater: 0,
          objectGuid: '',
          object_begin_tijd: '',
          object_eind_tijd: '',
          object_guid: '',
          objecttype: '',
          onderhoudsfirma: '',
          ontv_toelaatbaar_peilst: 0,
          ontv_waterpeil: 0,
          ontw_doorl_grond: 0,
          ontw_hgt_grondwaterstand: 0,
          ontw_oppervlak: 0,
          ontwerppeil_ontv_water: 0,
          openbare_ruimte: '',
          ophanginrichting: '',
          opp_water_straat: 0,
          pompcapaciteit: 0,
          pomptype: '',
          porositeit: 0,
          prognose_draaiuren: 0,
          putafmeting: '',
          putcode: '',
          putdekseltype: '',
          putdiepte: 0,
          rayon: '',
          reg_begin: '',
          reg_eind: '',
          reinigingscyclus: '',
          reinigingsjaar: '',
          relatieve_hoogteligging: 0,
          revisietekening: '',
          rioolputhfdtype_gwsw: '',
          rioolputsubtype_gwsw: '',
          rioolputtype: '',
          rioolputtype_gwsw: '',
          rl_voorziening_id: '',
          status: '',
          std_beheercluster: '',
          std_beheerder_vakgeb: '',
          std_domein: '',
          std_funderingstype: '',
          std_grondsoort: '',
          std_kleptype: '',
          std_materiaal_put: '',
          std_putdekseltype: '',
          std_rioolputtype: '',
          std_structuurelement: '',
          stelsel_id: '',
          strategisch: '',
          structuurelement: '',
          subcategorie: '',
          sw_gebied_id: '',
          tekening: '',
          telemetrie: '',
          terugslagklep: '',
          toelichting: '',
          type_leidingelement: '',
          type_put_plus: '',
          uitschakelpeil: 0,
          verharding_wegdek: '',
          volgend_reinigingsjaar: '',
          vorm_gwsw: '',
          vorm_toegang: '',
          wanddikte: 0,
          waterpeil: 0,
          wijk: '',
          woonplaats: '',
          x62_cluster_aard: '',
          x62_funderingstype_gwsw: '',
          x62_infiltratieputtype: '',
          x62_lengte_deksel: 0,
          x62_lozingswerktype: '',
          x62_piek_emissie_10_jaar: 0,
          x62_piek_emissie_10_jaar_bzv: 0,
          x62_piek_emissie_2_jaar: 0,
          x62_piek_emissie_2_jaar_bzv: 0,
          x62_piek_emissie_5_jaar: 0,
          x62_piek_emissie_5_jaar_bzv: 0,
          x62_pompopstelling: '',
          x62_standaard_lozingswerktype: '',
          x62_std_categorie: '',
          x62_std_hoofdcategorie: '',
          x62_std_infiltratieputtype: '',
          x62_std_rayon: '',
          x62_std_subcategorie: '',
          ...params,
        };
        return rp;
      case 'Mechleiding':
        const ml: MechLeiding = {
          aanlegjaar: 0,
          aantal_buizen: 0,
          afbeelding: '',
          afwijkendedieptelegging: 0,
          bbv: '',
          begin_tijd: '',
          beheercluster: '',
          beheerder: '',
          beheerder_vakgeb: '',
          bemalingsgebied: '',
          bestek_nr: '',
          bovenliggende_verharding: '',
          breedte: 0,
          buistype: '',
          buurt: '',
          categorie: '',
          children: undefined,
          clazz: '',
          cons_onderdeel_id: '',
          detailverwijzing: '',
          diameter: 0,
          diepte_begin: 0,
          diepte_eind: 0,
          diepte_max: 0,
          domein: '',
          drukklasse: '',
          eind_tijd: '',
          eisvoorzorgsmaatregel: '',
          fid: 0,
          funderingstype: '',
          gemeente: '',
          geometrie: undefined,
          geonauwkeurigheidxy: 0,
          grondsoort: '',
          hoofdcategorie: '',
          hoogte: 0,
          id: 0,
          imgeo_id: '',
          lengte: 0,
          leverancier_fabrikant: '',
          lozingsput_id: '',
          materiaal_gwsw: '',
          materiaal_leiding: '',
          materiaal_rioolleiding: '',
          mech_leiding_id: '',
          mech_leidingtype_gwsw: '',
          objectGuid: '',
          object_begin_tijd: '',
          object_eind_tijd: '',
          object_guid: '',
          objecttype: '',
          ontluchtingspunten: 0,
          openbare_ruimte: '',
          persleidingtype: '',
          pompput_id: '',
          product_leiding: '',
          rayon: '',
          reg_begin: '',
          reg_eind: '',
          revisietekening: '',
          status: '',
          status_functioneren: '',
          std_beheercluster: '',
          std_beheerder_vakgeb: '',
          std_buistype: '',
          std_domein: '',
          std_grondsoort: '',
          std_materiaal_rioolleiding: '',
          std_persleidingtype: '',
          std_stelseltype: '',
          std_structuurelement: '',
          stelsel_id: '',
          stelseltype: '',
          stroomgebied: '',
          structuurelement: '',
          subcategorie: '',
          sw_gebied_id: '',
          toegankelijk: '',
          toelichting: '',
          toelichting_imkl: '',
          type_leiding: '',
          verbindingstype: '',
          verhoogd_risico: '',
          vervuilingsgraad: 0,
          vorm: '',
          wanddikte: 0,
          wandruwheid: 0,
          wandruwheid_bb: 0,
          wandruwheid_bo: 0,
          waterslagvoorziening: '',
          wijk: '',
          wion_thema: '',
          woonplaats: '',
          x62_cluster_aard: '',
          x62_std_categorie: '',
          x62_std_hoofdcategorie: '',
          x62_std_rayon: '',
          x62_std_subcategorie: '',
          ...params,
        };
        return ml;
      case 'Vrijvleiding':
        const vl: VrijvLeiding = {
          aanlegjaar: 0,
          aant_ie_bedrijven: 0,
          aant_ie_recreatie: 0,
          aantal_aansl_woningen: 0,
          aantal_buizen: 0,
          afbeelding: '',
          afvoer_dwa: 0,
          afvoer_rwa: 0,
          afwijkendedieptelegging: 0,
          baa_deformatie: 0,
          bab_scheur: 0,
          bac_breuk_instorting: 0,
          bad_defect_metselwerk: 0,
          bae_ontbrekend_metslspecie: 0,
          baf_oppervlakteschade: 0,
          bag_instekende_inlaat: 0,
          bah_defect_aansluiting: 0,
          bai_indring_afdichtingsmat: 0,
          bai_indring_afdichtingsring: 0,
          bai_indring_ander_afdichting: 0,
          baj_axiaal: 0,
          baj_hoekverdraaiing: 0,
          baj_radiaal: 0,
          baj_verpl_verbinding: 0,
          bak_defect_lining: 0,
          bal_defect_reparatie: 0,
          bam_lasfouten: 0,
          ban_poreuze_buis: 0,
          bba_wortels: 0,
          bbb_aangeh_afzettingen: 0,
          bbc_bezonken_afzettingen: 0,
          bbd_binnendringen_grond: 0,
          bbe_andere_obstakels: 0,
          bbf_infiltratie: 0,
          bbv: '',
          bdd_waterpeil: 0,
          begin_tijd: '',
          beginput_id: '',
          beheercluster: '',
          beheerder: '',
          beheerder_vakgeb: '',
          bemalingsgebied: '',
          berging: 0,
          bestek: '',
          bestek_nr: '',
          bob_begin_actueel: 0,
          bob_begin_ontwerp: 0,
          bob_eind_actueel: 0,
          bob_eind_ontwerp: 0,
          bovenliggende_verharding: '',
          breedte: 0,
          buislengte: 0,
          buistype: '',
          buisverbinding: '',
          buisvorm: '',
          buurt: '',
          capaciteit_spoelvoorz: 0,
          categorie: '',
          children: undefined,
          clazz: '',
          datum_bob_begin: '',
          datum_bob_eind: '',
          detailverwijzing: '',
          diameter: 0,
          domein: '',
          drainagetype: '',
          eind_tijd: '',
          eindput_id: '',
          eisvoorzorgsmaatregel: '',
          fid: 0,
          functie_vrijv_leiding: '',
          funderingstype: '',
          gemeente: '',
          geometrie: undefined,
          geonauwkeurigheidxy: 0,
          geotextiel_inf_deel: '',
          grondeigendom: '',
          grondsoort: '',
          grondwaterstand: '',
          hoofdcategorie: '',
          hoogte: 0,
          id: 0,
          imgeo_id: '',
          infiltratieriooltype: '',
          inspectie_bestand: '',
          inspectiecode: '',
          inspectiedatum: '',
          inspectiejaar: '',
          inspectienaam: '',
          inspectietechniek: '',
          kast_id: '',
          kl_link: '',
          knoopnummer_beginput: 0,
          knoopnummer_eindput: 0,
          lengte: 0,
          leverancier_fabrikant: '',
          materiaal_gwsw: '',
          materiaal_inf_deel: '',
          materiaal_leiding: '',
          materiaal_rioolleiding: '',
          objectGuid: '',
          object_begin_tijd: '',
          object_eind_tijd: '',
          object_guid: '',
          objecttype: '',
          onderhoudjaar: 0,
          ontgravingsmethode: '',
          ontv_toelaatbaar_peilst: 0,
          ontv_waterpeil: 0,
          ontw_doorl_grond: 0,
          ontw_hgt_grondwaterstand: 0,
          ontw_oppervlak: 0,
          openbare_ruimte: '',
          oppervlak_gesloten_wegen: 0,
          oppervlak_groen: 0,
          oppervlak_open_wegen: 0,
          oppervlak_plat_dak: 0,
          oppervlak_schuin_dak: 0,
          orig_id: 0,
          product_leiding: '',
          rayon: '',
          reg_begin: '',
          reg_eind: '',
          revisietekening: '',
          riool_drainage: '',
          sleuf_breedte: 0,
          sleuf_inhoud: 0,
          soort_locatie: '',
          spiegelverhang_dwa: 0,
          spiegelverhang_rwa: 0,
          status: '',
          status_functioneren: '',
          std_beheercluster: '',
          std_beheerder_vakgeb: '',
          std_buistype: '',
          std_buisverbinding: '',
          std_domein: '',
          std_drainagetype: '',
          std_funderingstype: '',
          std_grondsoort: '',
          std_infiltratieriooltype: '',
          std_materiaal_rioolleiding: '',
          std_stelseltype: '',
          std_strengtype: '',
          std_structuurelement: '',
          stelsel_id: '',
          stelseltype: '',
          strategisch: '',
          strengcode: '',
          strengtype: '',
          stroomgebied: '',
          structuurelement: '',
          subcategorie: '',
          sw_gebied_id: '',
          tekening: '',
          toegankelijk: '',
          toelichting: '',
          type_leiding: '',
          verbindingstype: '',
          verharding_wegdek: '',
          verhoogd_risico: '',
          verloren_berging: 0,
          vervuilingsgraad: 0,
          video_bestand: '',
          video_bestand_map: '',
          video_inspectie_bestand: '',
          vorm: '',
          vrijverval_leidingsubtype: '',
          vrijverval_leidingtype: '',
          wanddikte: 0,
          wandruwheid: 0,
          wandruwheid_bb: 0,
          wandruwheid_bo: 0,
          wijk: '',
          wion_thema: '',
          woonplaats: '',
          x62_aant_aansl_inwoner: 0,
          x62_bouwjaar_pomp: 0,
          x62_cluster_aard: '',
          x62_dikte_lining: 0,
          x62_funderingstype_gwsw: '',
          x62_ledigingspomp_id: '',
          x62_materiaal_lining: '',
          x62_pomptype: '',
          x62_soort_lining: '',
          x62_spoeltype: '',
          x62_std_categorie: '',
          x62_std_hoofdcategorie: '',
          x62_std_pomptype: '',
          x62_std_rayon: '',
          x62_std_spoeltype: '',
          x62_std_subcategorie: '',
          x62_stroomsnelheid_dwa: 0,
          x62_stroomsnelheid_rwa: 0,
          x62_telemetrie: '',
          x62_uniek_nummer: 0,
          x62_video_inspectie_bestanden: '',
          x62_waterpeil: 0,
          ...params,
        };
        return vl;
      default:
        throw new Error('Featuretype not implemented: ' + type);
    }
  }
}
