package nl.b3p.viewer.userlayer;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.sql.Connection;
import java.sql.SQLException;

public class Oracle implements DataBase {
    private static final Log LOG = LogFactory.getLog(Oracle.class);
    private final Connection connection;

    public Oracle(Connection connection) {
        this.connection = connection;
    }

    @Override
    public String preValidateView(String tableName, String filterSQL) {
        // TODO implement
        return null;
    }

    @Override
    public String getGtPkMetadataDDL() {
        return "CREATE TABLE gt_pk_metadata (\n" +
                "  table_schema VARCHAR2(32) NOT NULL,\n" +
                "  table_name VARCHAR2(120) NOT NULL,\n" +
                "  pk_column VARCHAR2(32) NOT NULL,\n" +
                "  pk_column_idx NUMBER(38),\n" +
                "  pk_policy VARCHAR2(32),\n" +
                "  pk_sequence VARCHAR2(64),\n" +
                "  constraint  chk_pk_policy check (pk_policy in ('sequence', 'assigned', 'autogenerated')));\n" +
                "\n" +
                "CREATE UNIQUE INDEX gt_pk_metadata_table_idx01 ON gt_pk_metadata (table_schema, table_name, pk_column);";
    }

    @Override
    public boolean createView(String viewName, String tableName, String filterSQL, String comments) {
        // TODO implement
        return false;
    }

    @Override
    public boolean dropView(String viewName) {
        // TODO implement
        return false;
    }

    @Override
    public boolean addToGtPKMetadata(String viewName, String tableName) {
        return false;
    }

    @Override
    public boolean removeFromGtPKMetadata(String viewName) {
        return false;
    }

    @Override
    public void close() {
        try {
            this.connection.close();
        } catch (SQLException throwables) {
            LOG.error("Probleem tijdens sluiten van connectie: " + throwables.getLocalizedMessage());
        }
    }
}
