


    create table form (
        id bigint generated by default as identity (start with 1),
        feature_type_name varchar(255),
        json clob,
        name varchar(255),
        sft bigint,
        primary key (id)
    );
    alter table form 
        add constraint FK300CC46F7FEB1E 
        foreign key (sft) 
        references feature_type;
