export enum AttributeTypeEnum {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  DATE = 'DATE',
  BOOLEAN = 'BOOLEAN',
  GEOMETRY_POINT = 'GEOMETRY_POINT',
  GEOMETRY_LINESTRING = 'GEOMETRY_LINESTRING',
  GEOMETRY_POLYGON = 'GEOMETRY_POLYGON',
}
